{ pkgs, inputs, ... }:
{
	imports = [
		./hardware-configuration.nix # NOTE: this gets generated by the install usb
	];

	hardware = {
		enableRedistributableFirmware = true;
		enableAllFirmware = true;
		opengl = {
			enable = true;
			driSupport = true;
			driSupport32Bit = true;
		};
		bluetooth = {
			enable = true;
			powerOnBoot = true;
		};
	};

	nixpkgs.config = {
		allowUnfree = true;
	};

	networking = {
		hostName = "boron";
		wireless.enable = true;
		networkmanager.enable = true;
	};

	time.timeZone = "Europe/Copenhagen";

	i18n = {
		defaultLocale = "C.UTF-8";
	};

	users = {
		users = {
			root.hashedPassword = "!"; # Do not make a password for the root account
			silver = {
				isNormalUser = true;
				description = "silver";
				extraGroups = [ "networkmanager" "wheel" ];
			};
		};
	};	

		home-manager = {
		extraSpecialArgs = { 
			inherit inputs; 
		};
		users = {
			"silver" = import ./silver.nix;
			# "root" = import ./root.nix;
		};
	};

	fonts.packages = with pkgs; [
		victor-mono
		source-han
		"0xproto"
	];

	programs = {
		nm-applet.enable = true; # for the network manager tray thingy
		zsh.enable = true; # terminal
		steam.enable = true;
		hyprland.enable = true;
	};

	services = {
		blueman.enable = true; # for bluetooth
		pipewire = {
			enable = true;
			alsa.enable = true;
			alsa.support32Bit = true;
			pulse.enable = true;
			jack.enable = true;
		};
		xserver.displayManager.sddm.enable = true;
	};

	systemd.timers."update-flake" = {
		wantedBy = [ "timers.target" ];
		timerConfig = {
			OnCalendar = "daily";
			Persistent = true;
		};
	};

	systemd.services."update-flake" = {
		path = with pkgs; [
			git
			openssh
			nix
			nixos-rebuild
		];
		script = ''
		[[ ! -d '/root/boron' ]] && cd /root && git clone git@github.com:silverstarstorm/boron
		cd /root/boron
		git pull
		nix flake update --commit-lock-file /root/boron
		nixos-rebuild switch --flake .
		git push
		'';
		serviceConfig = {
			Type = "oneshot";
			User = "root";
		};
	};

	# enable v4l2loopback for obs virtual camera
	boot.kernelModules = [
		"v4l2loopback"
	];

	boot.extraModprobeConfig = ''
		options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
	'';

	# This value determines the NixOS release from which the default
	# settings for stateful data, like file locations and database versions
	# on your system were taken. It‘s perfectly fine and recommended to leave
	# this value at the release version of the first install of this system.
	# Before changing this value read the documentation for this option
	# (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
	system.stateVersion = "24.05"; # Did you read the comment?
}
